# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='x_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='beacon',
            name='y_position',
            field=models.IntegerField(default=0),
        ),
    ]
